name: Starter Workflow
on: [workflow_dispatch, push, pull_request]

jobs:
  call-create-github-release-workflow:
    uses: Keyfactor/actions/.github/workflows/github-release.yml@main

  get-manifest-properties:
    runs-on: windows-latest
    outputs:
      update_catalog: ${{ steps.read-json.outputs.update_catalog }}
      integration_type:  ${{ steps.read-json.outputs.integration_type }}
    steps:
      - uses: actions/checkout@v3
      - name: Store json
        id: store-json
        shell: pwsh
        run: |
          $json = Get-Content integration-manifest.json | ConvertFrom-Json
          echo "::set-output name=update_catalog::$(echo $json.update_catalog)"
          echo "::set-output name=integration_type::$(echo $json.integration_type)"

  call-dotnet-build-and-release-workflow:
    needs: [call-create-github-release-workflow]
    uses: Keyfactor/actions/.github/workflows/dotnet-build-and-release.yml@main
    with:
      release_version: ${{ needs.call-create-github-release-workflow.outputs.release_version }}
      release_url: ${{ needs.call-create-github-release-workflow.outputs.release_url }}
      release_dir: EXAMPLE_SOLUTION/bin/Release/BUILD_TARGET # TODO: set build output directory to upload as a release, relative to checkout workspace
    secrets: 
      token: ${{ secrets.PRIVATE_PACKAGE_ACCESS }}

  call-generate-readme-workflow:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: Keyfactor/actions/.github/workflows/generate-readme.yml@main
    secrets:
      token: ${{ secrets.APPROVE_README_PUSH }}

  call-update-catalog-workflow:
    needs: get-manifest-properties
    if: needs.get-manifest-properties.outputs.update_catalog == 'True' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    uses: Keyfactor/actions/.github/workflows/update-catalog.yml@main
    secrets: 
      token: ${{ secrets.SDK_SYNC_PAT }}

  call-update-store-types-workflow:
    needs: get-manifest-properties
    if: needs.get-manifest-properties.outputs.integration_type == 'orchestrator' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    uses: Keyfactor/actions/.github/workflows/update-store-types.yml@main
    secrets: 
      token: ${{ secrets.UPDATE_STORE_TYPES }}
