name: Keyfactor Merge Cert Store Types
on: [workflow_dispatch]

jobs:
  get-manifest-properties:
    runs-on: windows-latest
    outputs:
      update_catalog: ${{ steps.read-json.outputs.update_catalog }}
      integration_type:  ${{ steps.read-json.outputs.integration_type }}
    steps:
      - uses: actions/checkout@v3
      - name: Store json
        id: read-json
        shell: pwsh
        run: |
          $json = Get-Content integration-manifest.json | ConvertFrom-Json
          $myvar = $json.integration_type
          echo "integration_type=$myvar" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

  dispatch-cert-store-merge:
    needs: get-manifest-properties
    if: needs.get-manifest-properties.outputs.integration_type == 'orchestrator' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    steps:
      - name: Trigger update-stores workflow on kfutil
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SDK_SYNC_PAT }}
          repository: keyfactor/kfutil
          event-type: targetRepo-event
          client-payload: '{"targetRepo": "${{github.repository}}"}' # This is the repository you want to update
